all:
  children:
    app:
      hosts:
        vm2:
          ansible_host: 192.168.10.31
          ansible_ssh_user: administrator
        vm3:
          ansible_host: 192.168.10.28
          ansible_ssh_user: administrator
    database:
      hosts:
        vm1:
          ansible_host: 192.168.10.29
          ansible_ssh_user: administrator
      vars:
        postgresql_version: "12"
        postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
        postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
    web:
      hosts:
        vm1:
          ansible_host: 192.168.10.29
          ansible_ssh_user: administrator
